CREATE TABLE IF NOT EXISTS ips (
  id VARCHAR(36) PRIMARY KEY,
  nombre VARCHAR(190) NOT NULL,
  nit VARCHAR(60) NULL,
  cod_hab VARCHAR(80) NULL,
  dpto VARCHAR(120) NULL,
  municipio VARCHAR(120) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

